### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9f in position 952: illegal multibyte   sequence

### ISSUE THREAD

**Issue by HDJN** [Borber/SBtream#1]
with open("config/config.json", "r") as load_f  这种格式需要指定下编码，要不然会报错，改成  with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式

**Comment by Borber** [comment]
> with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式

好的 谢谢

**Comment by Borber** [comment]
> with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式

我这边尝试了 也还是报错 您那边这样解决了吗?

**Comment by HDJN** [comment]
> 
> 
> > with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式
> 
> 我这边尝试了 也还是报错 您那边这样解决了吗?

其他文件这种格式的也改了吗

**Comment by Borber** [comment]
> > > with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式
> > 
> > 
> > 我这边尝试了 也还是报错 您那边这样解决了吗?
> 
> 其他文件这种格式的也改了吗，其他文件有这种格式的，也需要修改。

好的 我再试试

**Comment by Borber** [comment]
> > > with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式
> > 
> > 
> > 我这边尝试了 也还是报错 您那边这样解决了吗?
> 
> 其他文件这种格式的也改了吗，其他文件有这种格式的，也需要修改。

已修复 感谢

**Comment by HDJN** [comment]
> 
> 
> > > > with open("config/config.json", "r") as load_f 这种格式需要指定下编码，要不然会报错，改成 with open("config/config.json", "r", encoding="utf-8") as load_f 这种格式
> > > 
> > > 
> > > 我这边尝试了 也还是报错 您那边这样解决了吗?
> > 
> > 
> > 其他文件这种格式的也改了吗，其他文件有这种格式的，也需要修改。
> 
> 已修复 感谢

不客气
